### PR TITLE
Fix URL for downloading the PHP manual

### PR DESCRIPTION
**Pull request by lcd047**
The URL for downloading the PHP manual should be the [official page][phpman].

[phpman]: http://www.php.net/download-docs.php

### CODE REVIEW

**Comment by thinca** [comment]
Thanks.
I followed the link, and I was redirected to http://php.net/download-docs.php (there is no `www.`).
Which is right URL?

**Comment by lcd047** [comment]
I'm not redirected from here, either from the www address to the non-www one or the other way around.  It seems to depend on the particular mirror you reach first.  I don't think it matters, the addresses should be the same for all intents and purposes.  That said however, this just my opinion, and I'm not an authority on the PHP site.  I suppose the right place to ask about such thing would be some PHP support forum, but I haven't really used PHP in 15+ years. :)

**Comment by thinca** [comment]
OK.  Maybe it is not really matter.

**Comment by thinca** [comment]
Thanks!

**Pull request merged**
